import 'package:flutter/material.dart';

Color blackColor = Colors.black;
Color whiteColor = Colors.white;
Color bgColor = const Color(0xFF222222);

String powerStatsText = 'QI';
String powerStatsText2 = 'STR';
String powerStatsText3 = 'SPD';
String powerStatsText4 = 'DEF';
String powerStatsText5 = 'PWR';
String powerStatsText6 = 'CBT';
String detailsAlterEgo = 'Alter Ego: ';
String placeOfBirthTitle = 'Place Of Birth: ';
String placeOfBirthError = 'No places found';
String firstAppearenceTitle = 'First Appearance: ';
String firstAppearenceError = 'No data found';
String occupationTitle = 'Occupation: ';
String occupationError = 'No Occupation found';
String baseTitle = 'Base: ';
String baseError = 'No base found';
String groupAffiliationTitle = 'Group Affiliation: ';
String groupAffiliationError = 'No Group Affiliation found';
String relativesTitle = 'Relatives: ';
String relativesError = 'No relatives found';
String raceError = 'No race found';
String realNameText = 'Real Name: ';
String raceText = 'Race: ';
String publisherText = 'Publisher: ';
String homeCoverImg = 'lib/assets/homeCover.png';
